---
- name: install | Copy kubelet and kube-proxy binary from download dir
  copy:
    src: "{{ local_release_dir }}/{{ item }}-{{ kube_version }}-{{ image_arch }}"
    dest: "{{ bin_dir }}/{{ item }}"
    mode: 0755
    remote_src: true
  loop:
    - kubelet
    - kube-proxy 
  tags:
    - kubelet
    - upgrade
  notify: 
    - Node | restart kubelet
    - Node | restart kube-proxy

- name: install | Copy socat wrapper for Container Linux with Docker
  command: "{{ docker_bin_dir }}/docker run --rm -v {{ bin_dir }}:/opt/bin {{ install_socat_image_repo }}:{{ install_socat_image_tag }}"
  args:
    creates: "{{ bin_dir }}/socat"
  when:
    - ansible_os_family in ['Flatcar Container Linux by Kinvolk']
    - container_manager == "docker"

- name: install | Copy socat wrapper for Container Linux with Containerd
  command: "{{ containerd_bin_dir }}/ctr run --rm --mount type=bind,src={{ bin_dir }},dst=/opt/bin,options=rbind:rw {{ install_socat_image_repo }}:{{ install_socat_image_tag }}"
  args:
    creates: "{{ bin_dir }}/socat"
  when:
    - ansible_os_family in ['Flatcar Container Linux by Kinvolk']
    - container_manager == "containerd"

- name: install | Copy socat wrapper for Container Linux with crio
  command: "podman run --rm --mount type=bind,source={{ bin_dir }},destination=/opt/bin,rw=true {{ install_socat_image_repo }}:{{ install_socat_image_tag }}"
  args:
    creates: "{{ bin_dir }}/socat"
  when:
    - ansible_os_family in ['Flatcar Container Linux by Kinvolk']
    - container_manager == "crio"
