---

- name: Ensure nodePort range is reserved
  sysctl:
    name: net.ipv4.ip_local_reserved_ports
    value: "{{ kube_apiserver_node_port_range }}"
    sysctl_set: yes
    sysctl_file: "{{ sysctl_file_path }}"
    state: present
    reload: yes
  when: kube_apiserver_node_port_range is defined
  tags:
    - kube-node

- name: Verify if br_netfilter module exists
  shell: "modinfo br_netfilter"
  environment:
    PATH: "{{ ansible_env.PATH }}:/sbin"  # Make sure we can workaround RH's conservative path management
  register: modinfo_br_netfilter
  failed_when: modinfo_br_netfilter.rc not in [0, 1]
  changed_when: false

- name: Verify br_netfilter module path exists
  file:
    path: /etc/modules-load.d
    state: directory

- name: Enable br_netfilter module
  modprobe:
    name: br_netfilter
    state: present
  when: modinfo_br_netfilter.rc == 0

- name: Persist br_netfilter module
  copy:
    dest: /etc/modules-load.d/salix-br_netfilter.conf
    content: br_netfilter
  when: modinfo_br_netfilter.rc == 0

# kube-proxy needs net.bridge.bridge-nf-call-iptables enabled when found if br_netfilter is not a module
- name: Check if bridge-nf-call-iptables key exists
  command: "sysctl net.bridge.bridge-nf-call-iptables"
  failed_when: false
  changed_when: false
  register: sysctl_bridge_nf_call_iptables

- name: Enable bridge-nf-call tables
  sysctl:
    name: "{{ item }}"
    state: present
    sysctl_file: "{{ sysctl_file_path }}"
    value: "1"
    reload: yes
  when: sysctl_bridge_nf_call_iptables.rc == 0
  with_items:
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-arptables
  - net.bridge.bridge-nf-call-ip6tables

- name: Modprode Kernel Module for IPVS
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
  - ip_vs
  - ip_vs_rr
  - ip_vs_wrr
  - ip_vs_sh
  when: kube_proxy_mode == 'ipvs'
  tags:
  - kube-node

- name: Modprobe nf_conntrack_ipv4 for kernels < 4.19
  modprobe:
    name: nf_conntrack_ipv4
    state: present
  register: enable_nf_conntrack
  ignore_errors: yes
  when: kube_proxy_mode == 'ipvs'
  tags:
    - kube-node

- name: Modprobe nf_conntrack for kernels >= 4.19
  modprobe:
    name: nf_conntrack
    state: present
  when:
    - enable_nf_conntrack is failed
    - kube_proxy_mode == 'ipvs'
  tags:
    - kube-node

- name: Persist ip_vs modules
  copy:
    dest: /etc/modules-load.d/kube_proxy-ipvs.conf
    content: |
      ip_vs
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      {% if enable_nf_conntrack is failed -%}
      nf_conntrack
      {%-   else -%}
      nf_conntrack_ipv4
      {%-   endif -%}
  when: kube_proxy_mode == 'ipvs'
  tags:
    - kube-node

- name: Write kube-proxy environment config file 
  template:
    src: "kube-proxy.env.j2"
    dest: "{{ kube_config_dir }}/kube-proxy.env"
    backup: yes
  notify: 
    - Node | restart kube-proxy
  tags:
    - kube-proxy 
- name: kubeconfig| Copy kubeconfig gen sh  to cert dir 
  template:
    src: "kube-proxy.sh.j2"
    dest: "{{ kube_config_dir }}/cert/kube-proxy.sh"
  delegate_to: localhost
  connection: local
  run_once: yes  
 
- name: kubeconfig | gen kubeconfig to cert dir 
  shell: "cd {{ kube_config_dir }}/cert && sh -x kube-proxy.sh"
  delegate_to: localhost
  connection: local
  run_once: yes 

- name: kubeconfig| Copy kube-proxy config config dir 
  copy:
    src: "{{ kube_config_dir }}/cert/kube-proxy.kubeconfig"
    dest: "{{ kube_config_dir }}/kube-proxy.kubeconfig"
  notify: 
    - Node | restart kube-proxy
  tags:
    - kube-proxy    

- name: Write kube-proxy config file
  template:
    src: "kube-proxy.{{ kubeletConfig_api_version }}.yaml.j2"
    dest: "{{ kube_config_dir }}/kube-proxy.yaml"
  notify: 
    - Node | restart kube-proxy
  tags:
    - kube-proxy 

- name: Write kube-proxy systemd init file
  template:
    src: "kube-proxy.service.j2"
    dest: "/etc/systemd/system/kube-proxy.service"
    backup: "yes"
  notify: 
    - Node | restart kube-proxy  
  tags:
    - kube-proxy

- name: flush_handlers and reload-systemd
  meta: flush_handlers

- name: Enable  kube-proxy
  service:
    name: kube-proxy
    enabled: yes
    state: started
  tags:
    - kube-proxy
  notify: 
    - Kubelet | restart kube-proxy

